
package cn.it.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentServicWS", targetNamespace = "string.cxf.it.cn", wsdlLocation = "http://localhost:8080/WebServiceSer/cxf/hello?wsdl")
public class StudentServicWS
    extends Service
{

    private final static URL STUDENTSERVICWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTSERVICWS_EXCEPTION;
    private final static QName STUDENTSERVICWS_QNAME = new QName("string.cxf.it.cn", "StudentServicWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServiceSer/cxf/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTSERVICWS_WSDL_LOCATION = url;
        STUDENTSERVICWS_EXCEPTION = e;
    }

    public StudentServicWS() {
        super(__getWsdlLocation(), STUDENTSERVICWS_QNAME);
    }

    public StudentServicWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTSERVICWS_QNAME, features);
    }

    public StudentServicWS(URL wsdlLocation) {
        super(wsdlLocation, STUDENTSERVICWS_QNAME);
    }

    public StudentServicWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTSERVICWS_QNAME, features);
    }

    public StudentServicWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServicWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServicePort")
    public StudentService getStudentServicePort() {
        return super.getPort(new QName("string.cxf.it.cn", "StudentServicePort"), StudentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServicePort")
    public StudentService getStudentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("string.cxf.it.cn", "StudentServicePort"), StudentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTSERVICWS_EXCEPTION!= null) {
            throw STUDENTSERVICWS_EXCEPTION;
        }
        return STUDENTSERVICWS_WSDL_LOCATION;
    }

}
