/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.action;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.qdu.model.*;
import com.qdu.struts.form.StuForm;
import com.qdu.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-10-2015
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" scope="request"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm= (UserForm) form;// TODO Auto-generated method stub
		
		String type1=request.getParameter("type1");
		
		if(type1==null)
		{
			type1="none";
		}
		response.setContentType("text/html");
		response.setCharacterEncoding("utf-8");
		//System.out.println(type1);
		if(type1.equals("login"))
		{
			userBO ubb=new userBO();
			//System.out.println(userForm.getUserno()+","+ userForm.getPassword()+","+userForm.getType());
			if(ubb.checkUserByType(userForm.getUserno(), userForm.getPassword(),userForm.getType()))
			{
				
				request.getSession().setAttribute("userForm",userForm);
				//LoginRecordBO lrb=new LoginRecordBO();
				//lrb.addLoginRecord(userForm.getUserno(),);
				if(userForm.getType().equals("manager")){
					UserForm uf=ubb.getUserForm(userForm.getUserno());
					request.setAttribute("uf",uf);
					LoginRecordBO lrb=new LoginRecordBO();
					lrb.addLoginRecord(userForm.getUserno(),uf.getJob());
					return mapping.findForward("manager");
				}else if(userForm.getType().equals("student"))
				//System.out.println((String)session.getAttribute("userno"));
				{
					StuBO sbb=new StuBO();
					StuForm sf=sbb.getStuBean(userForm.getUserno());
					request.setAttribute("sf",sf);
					LoginRecordBO lrb=new LoginRecordBO();
					lrb.addLoginRecord(userForm.getUserno(),userForm.getType());
					return mapping.findForward("student");
				}
				else 
				{
					return mapping.findForward("loginUI");
				}
			}else
			{
				return mapping.findForward("err");
			}
		}else if(type1.equals("loginInfo"))
		{
			UserForm uf=(UserForm)request.getSession().getAttribute("userForm");
			if(uf==null)
			{
				return mapping.findForward("loginUI");
			}else{
				
				String type=uf.getType();
				if(type.equals("manager")){
					userBO ubb=new userBO();
					UserForm uf1=ubb.getUserForm(uf.getUserno());
					request.setAttribute("uf",uf1);
					
					return mapping.findForward("manager");
				}else if(type.equals("student"))
				//System.out.println((String)session.getAttribute("userno"));
				{
					StuBO sbb=new StuBO();
					StuForm sf=sbb.getStuBean(uf.getUserno());
					request.setAttribute("sf",sf);
					
					return mapping.findForward("student");
				}else{
					return mapping.findForward("err");
				}
			}
			
		}else if(type1.equals("changePassword"))
		{
			UserForm uf=(UserForm)request.getSession().getAttribute("userForm");
			if(uf==null)
			{
				return mapping.findForward("loginUI");
			}else{
				
				String type=uf.getType();
				if(type.equals("manager")){
					
					request.setAttribute("uf",uf);
					
					return mapping.findForward("changePassword");
				}else if(type.equals("student"))
				//System.out.println((String)session.getAttribute("userno"));
				{
					//StuBO sbb=new StuBO();
					//StuForm sf=sbb.getStuBean(uf.getUserno());
					request.setAttribute("uf",uf);
					
					return mapping.findForward("changePassword");
				}else{
					return mapping.findForward("loginUI");
				}
			}
			
		}
		else if(type1.equals("checkAgain"))
		{
			UserForm uf=(UserForm)request.getSession().getAttribute("userForm");
			if(uf==null)
			{
				return mapping.findForward("loginUI");
			}else{
				
				String type=uf.getType();
				if(type.equals("manager")){
					String password=userForm.getPassword();
					String passwd=uf.getPassword();
					//System.out.println(password);
					if(password.equals(passwd))
					{
						request.setAttribute("uf",uf);
						return mapping.findForward("newPassword");
					}else{
						request.setAttribute("uf",uf);
						return mapping.findForward("changePassword");
					}
				}else if(type.equals("student"))
				//System.out.println((String)session.getAttribute("userno"));
				{
					String password=userForm.getPassword();
					String passwd=uf.getPassword();
					//System.out.println(password);
					if(password.equals(passwd))
					{
						request.setAttribute("uf",uf);
						return mapping.findForward("newPassword");
					}else{
						request.setAttribute("uf",uf);
						return mapping.findForward("changePassword");
					}
					//StuBO sbb=new StuBO();
					//StuForm sf=sbb.getStuBean(uf.getUserno());
					//request.setAttribute("uf",uf);
					
					//return mapping.findForward("changePassword");
				}else{
					return mapping.findForward("loginUI");
				}
			}
			
		}	
		else if(type1.equals("martch"))
		{
			UserForm uf=(UserForm)request.getSession().getAttribute("userForm");
			if(uf==null)
			{
				return mapping.findForward("loginUI");
			}else{
				
				String type=uf.getType();
				if(type.equals("manager")){
					String password=userForm.getPassword();
					String passwd=uf.getPassword();
					//System.out.println(password);
					if(password.equals(passwd))
					{
						request.setAttribute("uf",uf);
						String newPass=userForm.getPassword();
						userBO sbb=new userBO();
						sbb.updatePassword(uf);
						userBO ubb=new userBO();
						UserForm uf1=ubb.getUserForm(uf.getUserno());
						request.setAttribute("uf",uf1);
						return mapping.findForward("manager");
					}else{
						request.setAttribute("uf",uf);
						return mapping.findForward("newPassword");
					}
				}else if(type.equals("student"))
				//System.out.println((String)session.getAttribute("userno"));
				{
					String password=userForm.getPassword();
					String passwd=uf.getPassword();
					//System.out.println(password);
					if(password.equals(passwd))
					{
						request.setAttribute("uf",uf);
						String newPass=userForm.getPassword();
						StuBO sbb=new StuBO();
						sbb.updatePassword(uf);
						StuForm sf=sbb.getStuBean(uf.getUserno());
						request.setAttribute("sf",sf);
						return mapping.findForward("student");
					}else{
						request.setAttribute("uf",uf);
						return mapping.findForward("newPassword");
					}
					//StuBO sbb=new StuBO();
					//StuForm sf=sbb.getStuBean(uf.getUserno());
					//request.setAttribute("uf",uf);
					
					//return mapping.findForward("changePassword");
				}else{
					return mapping.findForward("loginUI");
				}
			}
			
		}
		
		else{
			//System.out.println("h");
			userBO ubb=new userBO();
			
			if(ubb.checkUser(userForm.getUserno(), userForm.getPassword()))
			{
				

				userForm.setType("manager");
				LoginRecordBO lrb=new LoginRecordBO();
				lrb.addLoginRecord(userForm.getUserno(),"sysmanager");
				request.getSession().setAttribute("userForm",userForm);
				//System.out.println((String)session.getAttribute("userno"));
				return mapping.findForward("ok");
			}else
			{
				return mapping.findForward("err");
			}
		
		}
		
	}
}