/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.action;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.qdu.model.InspectBO;
import com.qdu.model.Mytools;
import com.qdu.model.NewsBO;
import com.qdu.model.StuBO;
import com.qdu.model.propertyBO;
import com.qdu.model.repaireBO;
import com.qdu.model.userBO;
import com.qdu.struts.form.InspectForm;
import com.qdu.struts.form.NewsForm;
import com.qdu.struts.form.PropertyForm;
import com.qdu.struts.form.RepaireForm;
import com.qdu.struts.form.StuForm;
import com.qdu.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2015
 * 
 * XDoclet definition:
 * @struts.action path="/news" name="newsForm" scope="request"
 */
public class NewsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NewsForm newsForm = (NewsForm) form;// TODO Auto-generated method stub
		String type=request.getParameter("type");
		if(type==null)
		{
			type="type";
		}
		//String type=request.getParameter("left");
		//System.out.println("type="+type);
		response.setContentType("text/html");
		response.setCharacterEncoding("utf-8");
		if(type.equals("message"))
		{
			return mapping.findForward("message");
		}else if(type.equals("loginUI"))
		{
			
				return mapping.findForward("loginUI");
			
			
		}else if(type.equals("sysmanager"))
		{
			
			return mapping.findForward("index");
		
		
	}else if(type.equals("guide"))
	{
		
		return mapping.findForward("guide");
	
	
}else if(type.equals("intro"))
{
	
	return mapping.findForward("intro");


}else if(type.equals("structure"))
{
	
	return mapping.findForward("struc");


}else if(type.equals("grade"))
{
	
		
		UserForm uf1=(UserForm)request.getSession().getAttribute("userForm");
		if(uf1==null)
		{
			return mapping.findForward("loginUI");
		}else{
			
			String type1=uf1.getType();
			if(type1.equals("manager")){
				userBO ubb=new userBO();
				UserForm uf2=ubb.getUserForm(uf1.getUserno());
				request.setAttribute("uf",uf2);
				
				
				
				String base=null;
				String con=null;
				InspectBO ib=new InspectBO();
				int pageSize=6;
				int pageNow=1;
				
				ArrayList<InspectForm> al=(ArrayList<InspectForm>)ib.getInspectionByPage(pageSize, pageNow,"inspection.yno",uf2.getYno(),"buildingno",uf2.getBno(),null,null);
				int pageCount=ib.getPageCount(pageSize,"inspection.yno",uf2.getYno(),"buildingno",uf2.getBno(),null,null);
				if(uf2.getJob().equals("sysmanager"))
				{
					al=(ArrayList<InspectForm>)ib.getInspectionByPage(pageSize, pageNow,null,null,null,null,null,null);

				    pageCount=ib.getPageCount(pageSize,null,null,null,null,null,null);
				}
				
				
				String[] p={pageCount+"","m_left",base,con};
				request.setAttribute("al", al);
				request.setAttribute("pageCount", p);
				request.setAttribute("uf", uf2);
				return mapping.findForward("m_grade");
				
			}else if(type1.equals("student"))
			//System.out.println((String)session.getAttribute("userno"));
			{
				int pageSize=10;
				int pageNow=1;
				String s_pageNow=request.getParameter("pageNow");
				if(s_pageNow!=null)
				{
				pageNow=Integer.parseInt(s_pageNow);
				}
				 

				
				StuBO sbb=new StuBO();
				StuForm sf=sbb.getStuBean(uf1.getUserno());
				InspectBO ibb=new InspectBO();
				int pageCount=ibb.getPageCount(pageSize, sf.getYno(), sf.getBuildingno(), sf.getDormno());
				String[] p={pageCount+""};
				ArrayList<InspectForm> al=(ArrayList<InspectForm>)ibb.getInspectFormByDormno(pageNow, pageSize, sf.getYno(), sf.getBuildingno(), sf.getDormno());
				request.setAttribute("al", al);
				request.setAttribute("pageCount", p);
				request.setAttribute("sf",sf);
				
				return mapping.findForward("grade");
			}else{
				return mapping.findForward("err");
			}
		}
		
	
	//return mapping.findForward("grade");


}else if(type.equals("left"))
{
	NewsBO ab=new NewsBO();
	int pageSize=6;
	int pageNow=1;
	String s_pageNow=request.getParameter("pageNow");
	if(s_pageNow!=null)
	{
	pageNow=Integer.parseInt(s_pageNow);
	}
	//System.out.println("type2="+type);
	ArrayList<NewsForm> al=(ArrayList)ab.getNewsFormWithSort(pageSize, pageNow, null, null, "news");
    int pageCount=ab.getPageCount(pageSize,null,"news");
	String[] p={pageCount+""};
	request.setAttribute("al", al);
	request.setAttribute("pageCount", p);
	return mapping.findForward("notice");


}else if(type.equals("addInfo"))
{
	
	FormFile formFile=newsForm.getAttach();
	if(formFile!=null)
	{
	String filename=formFile.getFileName();
	//System.out.println("filename="+filename);
	
	InputStream is=null;
	OutputStream os=null;
	newsForm.setNewscon(filename);
	try {
		is=formFile.getInputStream();
		String keepFilePath=this.getServlet().getServletContext().getRealPath("/images");
		//System.out.println("keepFilePath="+keepFilePath+" ");
		Mytools mt=new Mytools();
		String newFileName=mt.getNewFileName(filename);
		newsForm.setAttachment(newFileName);
		os=new FileOutputStream(keepFilePath+"\\"+newFileName);
		int len=0;
		byte []bytes=new byte[1024];
		while((len=is.read(bytes))>0)
		{
			os.write(bytes,0,len);
		}
		
		
	} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	} finally{
		try {
			is.close();
			os.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	
	}
	
	
	
	
	
	
	//System.out.println("start1=");
	NewsBO ab=new NewsBO();
	ab.addNews(newsForm);
	int pageSize=6;
	int pageNow=1;
	String s_pageNow=request.getParameter("pageNow");
	if(s_pageNow!=null)
	{
	pageNow=Integer.parseInt(s_pageNow);
	}
	//System.out.println("type2="+type);
	ArrayList<NewsForm> al=(ArrayList)ab.getNewsFormWithSort(pageSize, pageNow, null, null, "news");
    int pageCount=ab.getPageCount(pageSize, null, "news");
	String[] p={pageCount+""};
	request.setAttribute("al", al);
	request.setAttribute("pageCount", p);	
	return mapping.findForward("notice");
}else if(type.equals("deleteInfo"))
	{
	String newsno=(String)request.getParameter("newsno");
	NewsBO ab=new NewsBO();
	ab.deleteNews(newsno);
	int pageSize=6;
	int pageNow=1;
	String s_pageNow=request.getParameter("pageNow");
	if(s_pageNow!=null)
	{
	pageNow=Integer.parseInt(s_pageNow);
	}
	//System.out.println("type2="+type);
	ArrayList<NewsForm> al=(ArrayList)ab.getNewsFormWithSort(pageSize, pageNow, null, null, "news");
    int pageCount=ab.getPageCount(pageSize, null, "news");
	String[] p={pageCount+""};
	request.setAttribute("al", al);
	request.setAttribute("pageCount", p);	
	return mapping.findForward("notice");
	
	}else if(type.equals("updateInfo"))
	{
		NewsBO ab=new NewsBO();
		//sbb.updateStu(stuForm);
		String newsno=request.getParameter("newsno");
		NewsForm nf=ab.getNewsFormByNewsno(newsno);
		request.setAttribute("nf", nf);
		return mapping.findForward("updateNews");
		
	}else if(type.equals("updateNews"))
	{
		//System.out.println("start1");
		FormFile formFile=newsForm.getAttach();
		//System.out.println("start2");
		if(formFile!=null)
		{
		//System.out.println("start3");
		String filename=formFile.getFileName();
		//System.out.println("filename="+filename);
		
		InputStream is=null;
		OutputStream os=null;
		newsForm.setNewscon(filename);
		try {
			is=formFile.getInputStream();
			String keepFilePath=this.getServlet().getServletContext().getRealPath("/images");
			//System.out.println("keepFilePath="+keepFilePath+" ");
			Mytools mt=new Mytools();
			String newFileName=mt.getNewFileName(filename);
			newsForm.setAttachment(newFileName);
			os=new FileOutputStream(keepFilePath+"\\"+newFileName);
			int len=0;
			byte []bytes=new byte[1024];
			while((len=is.read(bytes))>0)
			{
				os.write(bytes,0,len);
			}
			
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			try {
				is.close();
				os.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		}
		
		NewsBO ab=new NewsBO();
		ab.updateNews(newsForm);
		NewsForm nf=ab.getNewsFormByNewsno(newsForm.getNewsno());
		request.setAttribute("nf", nf);
		return mapping.findForward("updateNews");
		
		
	}else if(type.equals("selectByNewsno"))
	{
		NewsBO ab=new NewsBO();
		//sbb.updateStu(stuForm);
		String newsno=request.getParameter("newsno");
		NewsForm nf=ab.getNewsFormByNewsno(newsno);
		request.setAttribute("nf", nf);
		return mapping.findForward("updateNews");
		
	}else if(type.equals("selectAttachment")||type.equals("selectAttach"))
	{
		String newscon=request.getParameter("newscon");
		String attachment=null;
		attachment=request.getParameter("attachment");
		if(attachment.equals("")||attachment.equals(" ")||attachment.equals("null"))
		{
			attachment=null;
		}
		if(attachment!=null)
		{
			//System.out.println("attac2="+(attachment!=null&&attachment.equals("")==false));
		response.setContentType("text/html;charset=utf-8");
		FileInputStream fis=null;
		OutputStream os=null;
		try {
			
		//String filterFileName=java.net.URLEncoder.encode("ssfbt.jpg","utf-8");
	
		//response.setHeader("Content-Disposition", "attachment;filename="+filterFileName);
		response.setHeader("Content-Disposition", "attachment;filename="+newscon);
		String filePath=this.getServlet().getServletContext().getRealPath("/images");
		String fileAllPath=filePath+"\\"+attachment;
				
		byte []buffer=new byte[1024];

		int len=0;
		
			fis=new FileInputStream(fileAllPath);
			os=response.getOutputStream();
			while((len=fis.read(buffer))>0)
			{
				os.write(buffer,0,len);
			}
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
			
			try {
			os.close();
			fis.close();
			}
			catch (IOException e) {
			//TODO Auto-generated catch block
				e.printStackTrace();
			}
          }
		}
		
		
		
		NewsBO ab=new NewsBO();
		int pageSize=6;
		int pageNow=1;
		String s_pageNow=request.getParameter("pageNow");
		if(s_pageNow!=null)
		{
		pageNow=Integer.parseInt(s_pageNow);
		}
		//System.out.println("type2="+type);
		ArrayList<NewsForm> al=(ArrayList)ab.getNewsFormWithSort(pageSize, pageNow, null, null, "news");
	    int pageCount=ab.getPageCount(pageSize,null,"news");
		String[] p={pageCount+""};
		request.setAttribute("al", al);
		request.setAttribute("pageCount", p);
		if(type.equals("selectAttachment"))
		{
			
		return mapping.findForward("notice");
		}else if(type.equals("selectAttach"))
		{
			
			return mapping.findForward("notices");
		}else
		{
			return mapping.findForward("notice");
		}

	}else if(type.equals("notices"))
	{
		NewsBO ab=new NewsBO();
		int pageSize=10;
		int pageNow=1;
		String s_pageNow=request.getParameter("pageNow");
		if(s_pageNow!=null)
		{
		pageNow=Integer.parseInt(s_pageNow);
		}
		//System.out.println("type2="+type);
		ArrayList<NewsForm> al=(ArrayList)ab.getNewsFormWithSort(pageSize, pageNow, null, null, "news");
	    int pageCount=ab.getPageCount(pageSize,null,"news");
		String[] p={pageCount+""};
		request.setAttribute("al", al);
		request.setAttribute("pageCount", p);
		return mapping.findForward("notices");

	}else if(type.equals("selectByBase"))
	{
		String base=newsForm.getType1();
		String basecon=newsForm.getNewscon();
		String b1=request.getParameter("base");
		String b2=request.getParameter("basecon");
		try {
			//b2=java.net.URLEncoder.encode(b2,"utf-8");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		//System.out.println("base="+b1);
		if(b1!=null)
		{
			base=b1;
		}
		if(b2!=null)
		{
			basecon=b2;
		}
		System.out.println("base="+base);
		System.out.println("basecon="+basecon);
		NewsBO ab=new NewsBO();
		//sbb.updateStu(stuForm);	
		int pageSize=10;
		int pageNow=1;
		String s_pageNow=request.getParameter("pageNow");
		if(s_pageNow!=null)
		{
		pageNow=Integer.parseInt(s_pageNow);
		}
		ArrayList<NewsForm> al=new ArrayList<NewsForm>();
		int pageCount=0;
		//System.out.println("type2="+type);
		if(base.equals("all"))
		{
			al=(ArrayList<NewsForm>)ab.getNewsFormWithSort(pageSize, pageNow, null, null, "news");
		    pageCount=ab.getPageCount(pageSize, null, "news");
			
		}else{
		al=(ArrayList<NewsForm>)ab.getNewsFormWithSortByBase(pageSize, pageNow, null, "news", base, basecon);
	    pageCount=ab.getPageCount(pageSize, "news", base, basecon);
		}
		String[] p={pageCount+""};
		String[] b={base,basecon};
		request.setAttribute("al", al);
		request.setAttribute("pageCount", p);
		//System.out.println("B1="+b[1]);
		request.setAttribute("b", b);
		return mapping.findForward("noticesByBase");
		
	}
	else{		
				NewsBO sbb=new NewsBO();
				//sbb.updateStu(stuForm);
				int pageSize=10;
				int pageNow=1;
				String s_pageNow=request.getParameter("pageNow");
				if(s_pageNow!=null)
				{
				pageNow=Integer.parseInt(s_pageNow);
				}
				ArrayList<NewsForm> aln=sbb.getNewsFormWithSort(pageSize, pageNow, null, null, "news");
				//ArrayList<NewsForm> aln=sbb.getNewsFormWithSort(pageSize, pageNow, null, null,"notice");
				ArrayList<NewsForm> al=sbb.getNewsFormWithSort(pageSize, pageNow, null, null,"news");
				ArrayList<NewsForm> al1=sbb.getNewsFormWithSort(pageSize, pageNow, null, "宿舍改造","news");
				ArrayList<NewsForm> al2=sbb.getNewsFormWithSort(pageSize, pageNow, null, "宿舍文化","news");
				ArrayList<NewsForm> al3=sbb.getNewsFormWithSort(pageSize, pageNow, null, "宿舍管理","news");
				ArrayList<NewsForm> al4=sbb.getNewsFormWithSort(pageSize, pageNow, null, "媒体关注","news");
				String AllPageCountn=sbb.getPageCount(pageSize, null,"notice")+"";
				String AllPageCount=sbb.getPageCount(pageSize, null,"news")+"";
				String pageCount1=sbb.getPageCount(pageSize, "宿舍改造","news")+"";
			    String pageCount2=sbb.getPageCount(pageSize, "宿舍文化","news")+"";
				String pageCount3=sbb.getPageCount(pageSize, "宿舍管理","news")+"";
				String pageCount4=sbb.getPageCount(pageSize, "媒体关注","news")+"";
				String pageCount[]={pageCount1,pageCount2,pageCount3,pageCount4,pageNow+"",AllPageCount,AllPageCountn};
				request.setAttribute("aln", aln);
				request.setAttribute("al", al);
				request.setAttribute("al1", al1);
				request.setAttribute("al2", al2);
				request.setAttribute("al3", al3);
				request.setAttribute("al4", al4);
				request.setAttribute("pageCount", pageCount);
				
				//request.setAttribute("pageNow", pageNow+"");
				//request.setAttribute("sf", stuForm);
				//System.out.println("action:pageNow="+pageNow);
				return mapping.findForward("root");
		}	
				
			
		
		
		
		
	}
}