/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.qdu.model.*;
import com.qdu.struts.form.BuildingForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2015
 * 
 * XDoclet definition:
 * @struts.action path="/queryByBuildingno" name="buildingForm" scope="request"
 */
public class QueryByBuildingnoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BuildingForm buildingForm = (BuildingForm) form;// TODO Auto-generated method stub
		BuildingBO bbb=new BuildingBO();
		BuildingBean bb=bbb.getBuildingsBean(buildingForm.getYno(), buildingForm.getBuildingno());
		YardBO ybb=new YardBO();
		YardBean yb=ybb.getYardsBean(buildingForm.getYno());
		request.setAttribute("yardsInfo", yb);
		request.setAttribute("bb",bb);
		return mapping.findForward("ok");
		
		
	}
}