/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.action;
import com.qdu.model.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.qdu.struts.form.UForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2015
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="uForm" scope="request"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UForm uForm = (UForm) form;// TODO Auto-generated method stub
		String name=uForm.getName();
		FormFile formFile=uForm.getMyPhoto();
		String filename=formFile.getFileName();
		//int filesize=formFile.getFileSize();
		//System.out.println(filename+" "+filesize);
		InputStream is=null;
		OutputStream os=null;
		try {
			is=formFile.getInputStream();
			String keepFilePath=this.getServlet().getServletContext().getRealPath("/images");
			System.out.println("keepFilePath="+keepFilePath+" ");
			Mytools mt=new Mytools();
			String newFileName=mt.getNewFileName(filename);
			os=new FileOutputStream(keepFilePath+"\\"+newFileName);
			int len=0;
			byte []bytes=new byte[1024];
			while((len=is.read(bytes))>0)
			{
				os.write(bytes,0,len);
			}
			
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			try {
				is.close();
				os.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		return null;
	}
}