
package cn.it.cxf;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "string.cxf.it.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @return
     *     returns java.util.List<cn.it.cxf.Student>
     */
    @WebMethod
    @WebResult(name = "student", targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "string.cxf.it.cn", className = "cn.it.cxf.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "string.cxf.it.cn", className = "cn.it.cxf.QueryResponse")
    public List<Student> query();

    /**
     * 
     * @param student
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "string.cxf.it.cn", className = "cn.it.cxf.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "string.cxf.it.cn", className = "cn.it.cxf.SaveResponse")
    public void save(
        @WebParam(name = "student", targetNamespace = "")
        Student student);

}
