
package cn.it.my1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebService1", targetNamespace = "ser.it.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebService1 {


    /**
     * 
     * @param name1
     * @param age1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "ser.it.cn", className = "cn.it.my1.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "ser.it.cn", className = "cn.it.my1.SayHelloResponse")
    @Action(input = "ser.it.cn/MyWebService1/sayHelloRequest", output = "ser.it.cn/MyWebService1/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "name1", targetNamespace = "")
        String name1,
        @WebParam(name = "age1", targetNamespace = "")
        int age1);

}
