/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-11-01 15:50:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <title>jQuery标签切换效果</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"imooc.css\" type=\"text/css\">\r\n");
      out.write("    <script src=\"http://libs.baidu.com/jquery/1.9.1/jquery.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!--代码部分begin-->\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("    <!--tag标题-->\r\n");
      out.write("    <div id=\"menu_female\">\r\n");
      out.write("        <h3>女装</h3>\r\n");
      out.write("        <div class=\"tag\" style=\"display: block;\">\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <p>第一类</p>\r\n");
      out.write("                    <a>1.衬衫</a>\r\n");
      out.write("                    <a>2.T恤</a>\r\n");
      out.write("                    <a>3.雪纺衫</a>\r\n");
      out.write("                    <a>4.针织衫</a>\r\n");
      out.write("                    <a>5.短外套</a>\r\n");
      out.write("                    <a>6.卫衣</a>\r\n");
      out.write("                    <a>7.小西裤</a>\r\n");
      out.write("                    <a>8.风衣</a>\r\n");
      out.write("                    <a>9.吊带背心</a>\r\n");
      out.write("                    <a>10.连衣裙</a>\r\n");
      out.write("                    <a name=\"setColor\">11.蕾丝连衣裙</a>\r\n");
      out.write("                    <a>12.复古连衣裙</a>\r\n");
      out.write("                    <a>13.印花连衣裙</a>\r\n");
      out.write("                    <a>14.真丝连衣裙</a>\r\n");
      out.write("                    <a>更多</a>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tag_More\" style=\"display:block\">\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <p>第二类</p>\r\n");
      out.write("                    <a>1.背带裤</a>\r\n");
      out.write("                    <a>2.哈伦裤</a>\r\n");
      out.write("                    <a>3.牛仔裤</a>\r\n");
      out.write("                    <a>4.休闲裤</a>\r\n");
      out.write("                    <a>5.小脚裤</a>\r\n");
      out.write("                    <a>6.西装裤</a>\r\n");
      out.write("                    <a>7.打底裤</a>\r\n");
      out.write("                    <a>8.阔脚裤</a>\r\n");
      out.write("                    <a>9.短裤</a>\r\n");
      out.write("                    <a>10.马甲/背心</a>\r\n");
      out.write("                    <a>11.羽绒服</a>\r\n");
      out.write("                    <a>12.棉服</a>\r\n");
      out.write("                    <a>13.夹克</a>\r\n");
      out.write("                    <a>14.POLO衫</a>\r\n");
      out.write("                    <a>更多</a>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"menu_con\">\r\n");
      out.write("        <h3>男装</h3>\r\n");
      out.write("        <div class=\"tag\" style=\"display:block\">\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <p>第一类</p>\r\n");
      out.write("                    <a>1.衬衫</a>\r\n");
      out.write("                    <a>2.T恤</a>\r\n");
      out.write("                    <a>3.牛仔裤</a>\r\n");
      out.write("                    <a>4.休闲裤</a>\r\n");
      out.write("                    <a>5.短裤</a>\r\n");
      out.write("                    <a>6.针织衫</a>\r\n");
      out.write("                    <a>7.西服</a>\r\n");
      out.write("                    <a>8.西裤</a>\r\n");
      out.write("                    <a>9.嘻哈裤</a>\r\n");
      out.write("                    <a>10.西服套装</a>\r\n");
      out.write("                    <a>11.马甲/背心</a>\r\n");
      out.write("                    <a name=\"setColor\">12.羽绒服</a>\r\n");
      out.write("                    <a>13.棉服</a>\r\n");
      out.write("                    <a>14.夹克</a>\r\n");
      out.write("                    <p>更多</p>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tag_More\" style=\"display:block\">\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <p>第二类</p>\r\n");
      out.write("                    <a>1.衬衫</a>\r\n");
      out.write("                    <a>2.T恤</a>\r\n");
      out.write("                    <a>3.牛仔裤</a>\r\n");
      out.write("                    <a name='setColor'>4.休闲裤</a>\r\n");
      out.write("                    <a>5.短裤</a>\r\n");
      out.write("                    <a>6.针织衫</a>\r\n");
      out.write("                    <a>7.西服</a>\r\n");
      out.write("                    <a>8.西裤</a>\r\n");
      out.write("                    <a>9.嘻哈裤</a>\r\n");
      out.write("                    <a>10.西服套装</a>\r\n");
      out.write("                    <a>11.马甲/背心</a>\r\n");
      out.write("                    <a>12.羽绒服</a>\r\n");
      out.write("                    <a>13.棉服</a>\r\n");
      out.write("                    <a>14.夹克</a>\r\n");
      out.write("                    <p>更多</p>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("    //找到男装下第一类衣服中的第一个p元素，并改变颜色\r\n");
      out.write("    //可以通过子类选择器  p:first-child 筛选出第一个p元素\r\n");
      out.write("    ?.css('color','#9932CC');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //找到男装下第一类衣服把a元素从顺序1-4加上颜色\r\n");
      out.write("    //可以通过基本筛选器lt,选择匹配集合中所有索引值小于给定index参数的元素\r\n");
      out.write("    //注意了index是从0开始计算，所以选在1-4,为对应的index就是4\r\n");
      out.write("   ?.css('color','red');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //找到男装所有a元素中属性名name=\"setColor\"的元素，并设置颜色\r\n");
      out.write("    //这里用的属性选择器[attribute='value']选择指定属性是给定值的元素\r\n");
      out.write("   ?.css('color','blue');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //不分男女，选中第一类衣服中第9个a元素，并改变颜色\r\n");
      out.write("    //这里用了nth-child 选择的他们所有父元素的第n个子元素\r\n");
      out.write("    ?.css('color','#66CD00');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //找到女装下第一类衣服，把a元素中包含文字\"更多\"的节点，改变颜色\r\n");
      out.write("    ?.css('color','#C71585');\r\n");
      out.write("</script>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
