/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-24-2015
 * 
 * XDoclet definition:
 * @struts.form name="accessToRecordForm"
 */
public class AccessToRecordForm extends ActionForm {
	/*
	 * Generated fields
	 */
private String accessTime;
	public String getAccessTime() {
	return accessTime;
}

public void setAccessTime(String accessTime) {
	this.accessTime = accessTime;
}

	/** buildingno property */
	private String buildingno;

	/** flag property */
	private String flag;

	/** accessdate property */
	private String accessdate;

	/** cardno property */
	private String cardno;

	/** yno property */
	private String yno;

	/** recordno property */
	private String recordno;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the buildingno.
	 * @return String
	 */
	public String getBuildingno() {
		return buildingno;
	}

	/** 
	 * Set the buildingno.
	 * @param buildingno The buildingno to set
	 */
	public void setBuildingno(String buildingno) {
		this.buildingno = buildingno;
	}

	/** 
	 * Returns the flag.
	 * @return String
	 */
	public String getFlag() {
		return flag;
	}

	/** 
	 * Set the flag.
	 * @param flag The flag to set
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/** 
	 * Returns the accessdate.
	 * @return String
	 */
	public String getAccessdate() {
		return accessdate;
	}

	/** 
	 * Set the accessdate.
	 * @param accessdate The accessdate to set
	 */
	public void setAccessdate(String accessdate) {
		this.accessdate = accessdate;
	}

	/** 
	 * Returns the cardno.
	 * @return String
	 */
	public String getCardno() {
		return cardno;
	}

	/** 
	 * Set the cardno.
	 * @param cardno The cardno to set
	 */
	public void setCardno(String cardno) {
		this.cardno = cardno;
	}

	/** 
	 * Returns the yno.
	 * @return String
	 */
	public String getYno() {
		return yno;
	}

	/** 
	 * Set the yno.
	 * @param yno The yno to set
	 */
	public void setYno(String yno) {
		this.yno = yno;
	}

	/** 
	 * Returns the recordno.
	 * @return String
	 */
	public String getRecordno() {
		return recordno;
	}

	/** 
	 * Set the recordno.
	 * @param recordno The recordno to set
	 */
	public void setRecordno(String recordno) {
		this.recordno = recordno;
	}
}