/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-13-2015
 * 
 * XDoclet definition:
 * @struts.form name="buildingForm"
 */
public class BuildingForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** stunum property */
	private int stunum;

	/** phone property */
	private String phone;

	/** buildingnum property */
	private String buildingnum;

	/** manager property */
	private String manager;

	/** levelnum property */
	private String levelnum;

	/** type property */
	private String type;

	/** roomnum property */
	private int roomnum;


	/** 
	 * Returns the stunum.
	 * @return String
	 */
	public int getStunum() {
		return stunum;
	}

	/** 
	 * Set the stunum.
	 * @param stunum The stunum to set
	 */
	public void setStunum(int stunum) {
		this.stunum = stunum;
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the buildingnum.
	 * @return String
	 */
	public String getBuildingnum() {
		return buildingnum;
	}

	/** 
	 * Set the buildingnum.
	 * @param buildingnum The buildingnum to set
	 */
	public void setBuildingnum(String buildingnum) {
		this.buildingnum = buildingnum;
	}

	/** 
	 * Returns the manager.
	 * @return String
	 */
	public String getManager() {
		return manager;
	}

	/** 
	 * Set the manager.
	 * @param manager The manager to set
	 */
	public void setManager(String manager) {
		this.manager = manager;
	}

	/** 
	 * Returns the levelnum.
	 * @return String
	 */
	public String getLevelnum() {
		return levelnum;
	}

	/** 
	 * Set the levelnum.
	 * @param levelnum The levelnum to set
	 */
	public void setLevelnum(String levelnum) {
		this.levelnum = levelnum;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the roomnum.
	 * @return String
	 */
	public int getRoomnum() {
		return roomnum;
	}

	/** 
	 * Set the roomnum.
	 * @param roomnum The roomnum to set
	 */
	public void setRoomnum(int roomnum) {
		this.roomnum = roomnum;
	}
	private String buildingno;

	public String getBuildingno() {
		return buildingno;
	}

	public void setBuildingno(String buildingno) {
		this.buildingno = buildingno;
	}
	private String yno;

	public String getYno() {
		return yno;
	}

	public void setYno(String yno) {
		this.yno = yno;
	}
}