/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-20-2015
 * 
 * XDoclet definition:
 * @struts.form name="inspectForm"
 */
public class InspectForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** mcdc property */
	private String mcdc;

	/** pmcw property */
	private String pmcw;

	/** cxxsj property */
	private String cxxsj;

	/** sum property */
	private String sum;

	/** kqqw property */
	private String kqqw;

	/** qbsj property */
	private String qbsj;

	/** wpbf property */
	private String wpbf;

	/** bzzt property */
	private String bzzt;

	/** dmyt property */
	private String dmyt;

	/** bno property */
	private String bno;

	/** dormno property */
	private String dormno;

	/** zsk property */
	private String zsk;

	/** datetime property */
	private String datetime;

	/** yno property */
	private String yno;

	/** zm property */
	private String zm;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the mcdc.
	 * @return String
	 */
	public String getMcdc() {
		return mcdc;
	}

	/** 
	 * Set the mcdc.
	 * @param mcdc The mcdc to set
	 */
	public void setMcdc(String mcdc) {
		this.mcdc = mcdc;
	}

	/** 
	 * Returns the pmcw.
	 * @return String
	 */
	public String getPmcw() {
		return pmcw;
	}

	/** 
	 * Set the pmcw.
	 * @param pmcw The pmcw to set
	 */
	public void setPmcw(String pmcw) {
		this.pmcw = pmcw;
	}

	/** 
	 * Returns the cxxsj.
	 * @return String
	 */
	public String getCxxsj() {
		return cxxsj;
	}

	/** 
	 * Set the cxxsj.
	 * @param cxxsj The cxxsj to set
	 */
	public void setCxxsj(String cxxsj) {
		this.cxxsj = cxxsj;
	}

	/** 
	 * Returns the sum.
	 * @return String
	 */
	public String getSum() {
		return sum;
	}

	/** 
	 * Set the sum.
	 * @param sum The sum to set
	 */
	public void setSum(String sum) {
		this.sum = sum;
	}

	/** 
	 * Returns the kqqw.
	 * @return String
	 */
	public String getKqqw() {
		return kqqw;
	}

	/** 
	 * Set the kqqw.
	 * @param kqqw The kqqw to set
	 */
	public void setKqqw(String kqqw) {
		this.kqqw = kqqw;
	}

	/** 
	 * Returns the qbsj.
	 * @return String
	 */
	public String getQbsj() {
		return qbsj;
	}

	/** 
	 * Set the qbsj.
	 * @param qbsj The qbsj to set
	 */
	public void setQbsj(String qbsj) {
		this.qbsj = qbsj;
	}

	/** 
	 * Returns the wpbf.
	 * @return String
	 */
	public String getWpbf() {
		return wpbf;
	}

	/** 
	 * Set the wpbf.
	 * @param wpbf The wpbf to set
	 */
	public void setWpbf(String wpbf) {
		this.wpbf = wpbf;
	}

	/** 
	 * Returns the bzzt.
	 * @return String
	 */
	public String getBzzt() {
		return bzzt;
	}

	/** 
	 * Set the bzzt.
	 * @param bzzt The bzzt to set
	 */
	public void setBzzt(String bzzt) {
		this.bzzt = bzzt;
	}

	/** 
	 * Returns the dmyt.
	 * @return String
	 */
	public String getDmyt() {
		return dmyt;
	}

	/** 
	 * Set the dmyt.
	 * @param dmyt The dmyt to set
	 */
	public void setDmyt(String dmyt) {
		this.dmyt = dmyt;
	}

	/** 
	 * Returns the bno.
	 * @return String
	 */
	public String getBno() {
		return bno;
	}

	/** 
	 * Set the bno.
	 * @param bno The bno to set
	 */
	public void setBno(String bno) {
		this.bno = bno;
	}

	/** 
	 * Returns the dormno.
	 * @return String
	 */
	public String getDormno() {
		return dormno;
	}

	/** 
	 * Set the dormno.
	 * @param dormno The dormno to set
	 */
	public void setDormno(String dormno) {
		this.dormno = dormno;
	}

	/** 
	 * Returns the zsk.
	 * @return String
	 */
	public String getZsk() {
		return zsk;
	}

	/** 
	 * Set the zsk.
	 * @param zsk The zsk to set
	 */
	public void setZsk(String zsk) {
		this.zsk = zsk;
	}

	/** 
	 * Returns the datetime.
	 * @return String
	 */
	public String getDatetime() {
		return datetime;
	}

	/** 
	 * Set the datetime.
	 * @param datetime The datetime to set
	 */
	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	/** 
	 * Returns the yno.
	 * @return String
	 */
	public String getYno() {
		return yno;
	}

	/** 
	 * Set the yno.
	 * @param yno The yno to set
	 */
	public void setYno(String yno) {
		this.yno = yno;
	}

	/** 
	 * Returns the zm.
	 * @return String
	 */
	public String getZm() {
		return zm;
	}

	/** 
	 * Set the zm.
	 * @param zm The zm to set
	 */
	public void setZm(String zm) {
		this.zm = zm;
	}
	private String yname;

	public String getYname() {
		return yname;
	}

	public void setYname(String yname) {
		this.yname = yname;
	}
}