/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2015
 * 
 * XDoclet definition:
 * @struts.form name="newsForm"
 */
public class NewsForm extends ActionForm {
	/*
	 * Generated fields
	 */
 private FormFile attach;
	public FormFile getAttach() {
	return attach;
}

public void setAttach(FormFile attach) {
	this.attach = attach;
}

	/** title property */
	private String title;

	/** mewscon property */
	private String newscon;

	/** newstime property */
	private String newstime;

	/** newsno property */
	private String newsno;

	/** attachment property */
	private String attachment;

	/** type property */
	private String type1;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the mewscon.
	 * @return String
	 */
	public String getNewscon() {
		return newscon;
	}

	/** 
	 * Set the mewscon.
	 * @param mewscon The mewscon to set
	 */
	public void setNewscon(String newscon) {
		this.newscon = newscon;
	}

	/** 
	 * Returns the newstime.
	 * @return String
	 */
	public String getNewstime() {
		return newstime;
	}

	/** 
	 * Set the newstime.
	 * @param newstime The newstime to set
	 */
	public void setNewstime(String newstime) {
		this.newstime = newstime;
	}

	/** 
	 * Returns the newsno.
	 * @return String
	 */
	public String getNewsno() {
		return newsno;
	}

	/** 
	 * Set the newsno.
	 * @param newsno The newsno to set
	 */
	public void setNewsno(String newsno) {
		this.newsno = newsno;
	}

	/** 
	 * Returns the attachment.
	 * @return String
	 */
	public String getAttachment() {
		return attachment;
	}

	/** 
	 * Set the attachment.
	 * @param attachment The attachment to set
	 */
	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType1() {
		return type1;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType1(String type1) {
		this.type1 = type1;
	}
}