/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-16-2015
 * 
 * XDoclet definition:
 * @struts.form name="stuForm"
 */
public class StuForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String password;

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	/** buildingno property */
	private String buildingno;

	/** phone property */
	private String phone;

	/** sex property */
	private String sex;

	/** stuno property */
	private String stuno;

	/** dormno property */
	private String dormno;

	/** name property */
	private String name;

	/** role property */
	private String role;

	/** intime property */
	private String intime;

	/** yno property */
	private String yno;

	/** major property */
	private String major;
	private String seminary;
	public String getSeminary() {
		return seminary;
	}

	public void setSeminary(String seminary) {
		this.seminary = seminary;
	}

	public String getBedno() {
		return bedno;
	}

	public void setBedno(String bedno) {
		this.bedno = bedno;
	}

	private String bedno;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the buildingno.
	 * @return String
	 */
	public String getBuildingno() {
		return buildingno;
	}

	/** 
	 * Set the buildingno.
	 * @param buildingno The buildingno to set
	 */
	public void setBuildingno(String buildingno) {
		this.buildingno = buildingno;
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the stuno.
	 * @return String
	 */
	public String getStuno() {
		return stuno;
	}

	/** 
	 * Set the stuno.
	 * @param stuno The stuno to set
	 */
	public void setStuno(String stuno) {
		this.stuno = stuno;
	}

	/** 
	 * Returns the dormno.
	 * @return String
	 */
	public String getDormno() {
		return dormno;
	}

	/** 
	 * Set the dormno.
	 * @param dormno The dormno to set
	 */
	public void setDormno(String dormno) {
		this.dormno = dormno;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the role.
	 * @return String
	 */
	public String getRole() {
		return role;
	}

	/** 
	 * Set the role.
	 * @param role The role to set
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/** 
	 * Returns the intime.
	 * @return String
	 */
	public String getIntime() {
		return intime;
	}

	/** 
	 * Set the intime.
	 * @param intime The intime to set
	 */
	public void setIntime(String intime) {
		this.intime = intime;
	}

	/** 
	 * Returns the yno.
	 * @return String
	 */
	public String getYno() {
		return yno;
	}

	/** 
	 * Set the yno.
	 * @param yno The yno to set
	 */
	public void setYno(String yno) {
		this.yno = yno;
	}

	/** 
	 * Returns the major.
	 * @return String
	 */
	public String getMajor() {
		return major;
	}

	/** 
	 * Set the major.
	 * @param major The major to set
	 */
	public void setMajor(String major) {
		this.major = major;
	}
}