/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qdu.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-10-2015
 * 
 * XDoclet definition:
 * @struts.form name="userForm"
 */
public class UserForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String type;


public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

private String intime;
	public String getIntime() {
	return intime;
}

public void setIntime(String intime) {
	this.intime = intime;
}

	/** username property */
	private String userno;

	/** password property */
	private String password;

	private String sex;
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getEname() {
		return ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getYno() {
		return yno;
	}

	public void setYno(String yno) {
		this.yno = yno;
	}

	public String getBno() {
		return bno;
	}

	public void setBno(String bno) {
		this.bno = bno;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	private String ename;
	private String address;
	private String phone;
	private String email;
	private String postcode;
	private String yno;
	private String bno;
	private int age;
	private String job;
	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUserno() {
		return userno;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUserno(String userno) {
		this.userno = userno;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	
}