$(function(){
	$('#box').panel({
		//id:'#pox',
		title:'面板',
		width:500,
		height:150,
		iconCls:'icon-search',
		left:200,
		cls:'a',
		headerCls:'d',
		bodyCls:'e',
		style:{
			'min-height':'200px',
		},
		//fit:true,
		//border:false,
		//doSize:false,
		//noheader:true,
		//content:'修改内容',
		collapsible:true,
		minimizable:true,
		maximizable:true,
		closable:true,
		//tools:'#tt',
		tools:[{
			iconCls:'icon-help',
			handler:function(){
				
			}
		},{
			iconCls:'icon-reload',
			handler:function(){
				$('#box').panel('refresh');
			}
		}],
		//collapsed:true,
		//minimized:true,
		//maximized:true,
		//closed:true,
		href:'www.baidu.com',
		loadingMessage:'loading。。。',
		extractor:function(data){
			return data.substring(0,3);
		},
		onBeforeLoad:function(){
			alert('远程加载之前');
			return false;
		},
		onLoad:function(){
			alert('远程加载之后');
		},
		onBeforeOpen:function(){
			alert('面板打开之前');
		},
		onOpen:function(){
			alert('面板打开之后');
		},
		onBeforeClose:function(){
			alert('面板关闭之前');
		},
		onClose:function(){
			alert('面板关闭之后');
		},
		onBeforeDestroy:function(){
			alert('面板销毁之前');
		},
		onDestroy:function(){
			alert('面板销毁之后');
		},
		onBeforeCollapse:function(){
			alert('面板折叠之前');
		},
		onCollapse:function(){
			alert('面板折叠之后');
		},
		onBeforeExpand:function(){
			alert('面板展开之前');
		},
		onExpand:function(){
			alert('面板展开之后');
		},
		onMaximize:function(){
			alert('面板最大化之后');
		},
		onRestore:function(){
			alert('面板还原之后');
		},
		onMinimize:function(){
			alert('面板最小化之后');
		},
		onResize:function(width,height){
			alert(width+"  "+height);
		},
		onMove:function(left,top){
			alert(left+"  "+top);
		},
		
		
	});
	$('#box').panel('panel').css('position','absolute');
	
	$(document).click(function(){
		//$('#box').panel('destroy');
		/*$('#box').panel('resize',{
			'width':200,
			'height':200,
		});*/
		$('#box').panel('move',{
			'left':200,
			'top':200,
		});
	});
	console.log($('#box').panel('options'));
	console.log($('#box').panel('header'));
	console.log($('#box').panel('body'));
	$('#box').panel('setTitle','标题');
	$('#box').panel('open',true);
	//$('#box').panel('maximize');
	//$('#box').panel('minimize');
	//$('#box').panel('restore');
	//$('#box').panel('collapse');
	//$('#box').panel('expand');
	
	
});